name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Generate MD5 hash for the built .exe
      run: |
        $filePath = "D:\a\Dota2Patcher\Dota2Patcher\Release\Dota2Patcher.exe"
        $hash = Get-FileHash $filePath -Algorithm MD5
        $hash.Hash | Out-File -FilePath build_hash.txt
        
    - name: Upload MD5 hash as artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-md5-hash
        path: build_hash.txt
